pipeline:

  publish:
    image: plugins/docker
    repo: ethicaljobs/composer-prestissimo
    secrets: [ docker_username, docker_password ]
    tags:
      - 'latest'
      - '${DRONE_TAG=${DRONE_COMMIT}}'
    when:
      event: tag

  notify-slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: deployments
    when:
      event: tag
