kind: pipeline
name: default

steps:

  - name: publish
    image: plugins/docker
    settings:
      repo: ethicaljobs/composer-prestissimo
      tags:
        - 'latest'
        - '${DRONE_TAG=${DRONE_COMMIT}}'
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password    
  